models/contacts.py
from sqlalchemy.orm import Mapped, mapped_column

from utils.db import db


class Contact(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    fullname: Mapped[str] = mapped_column(nullable=False)
    email: Mapped[str] = mapped_column()
    phone: Mapped[str]

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from utils.db import db
from routes.contacts import contacts
from dotenv import load_dotenv
import os

load_dotenv()

app = Flask(__name__)

app.secret_key = os.environ.get('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DB_URL')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)
with app.app_context():
    db.create_all()

app.register_blueprint(contacts)

routes/contacts.py
from flask import (Blueprint, flash, jsonify, redirect, render_template,
                   request, url_for)

from models.contacts import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)


@contacts.route('/', methods=["GET"])
def index():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)


@contacts.route('/new', methods=['POST'])
def add_contact():
    try:
        fullname, email, phone = request.form.values()
        contact = Contact(fullname, email, phone)
        db.session.add(contact)
        db.session.commit()
        flash('Contact added successfully!')
        return redirect(url_for('contacts.index'))
    except Exception:
        return redirect(url_for('contacts.index'), 501)


@contacts.route('/update/<id>', methods=['GET', 'POST'])
def update(id):
    contact = Contact.query.get(id)
    if not contact:
        return "Contacto no encontrado", 404
    if request.method == "GET":
        contact = Contact.query.get(id)
        return render_template('update.html', contact=contact)
    else:
        fullname, email, phone = request.form.values()
        contact.fullname = fullname
        contact.email = email
        contact.phone = phone
        db.session.commit()
        flash('Contact updated successfully!')
        return redirect(url_for('contacts.index'))


@contacts.route('/delete/<id>', methods=['GET', 'POST'])
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    flash('Contact deleted successfully!')
    return redirect(url_for('contacts.index'))


@contacts.route('/about', methods=["GET"])
def about():
    return render_template('about.html')


@contacts.route('/test', methods=["POST"])
def test():
    data = request.get_json()
    nombre = data.get('nombre')
    edad = data.get('edad')
    print([nombre, edad])
    return jsonify(data)

templates/about.html
{% extends 'layout.html' %} {% block content %}
<section class="row p-5">
  <div class="col-12 p-5">
    <article class="card card-body mx-auto" style="width: 80%">
      <h1 class="card-title">About</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur
        alias facilis dignissimos accusantium. Nostrum voluptas deleniti quasi
        commodi, consequatur illo ducimus asperiores ipsum suscipit animi
        consequuntur nemo adipisci exercitationem cupiditate aut recusandae quo
        corporis debitis, dolorem nobis. Beatae doloremque aspernatur iste
        ratione distinctio assumenda eveniet enim maxime, temporibus,
        consequatur quod hic perspiciatis praesentium placeat pariatur fuga.
        Corporis doloribus adipisci accusamus beatae officiis fugiat
        reprehenderit aperiam aspernatur ad, consectetur exercitationem facilis
        illo quisquam quos, amet eaque eveniet harum autem porro doloremque
        voluptas quaerat consequuntur? Assumenda, aliquam eaque provident vel
        reiciendis quibusdam cumque molestias rem laboriosam amet saepe
        veritatis facere ducimus iure ut. Molestiae, veritatis. Totam quam sed
        vel id voluptatum animi tempora nihil illum. Totam obcaecati illo
        reiciendis accusamus magni dolore sed quo eum amet doloremque iusto
        delectus velit nam recusandae quas accusantium, repellat numquam vitae!
        Voluptatibus provident cumque, tempore eaque impedit veniam culpa
        obcaecati fugiat. Illo ipsam tempore voluptates possimus? Ratione rem
        suscipit expedita voluptate quidem et, cumque magni doloribus
        necessitatibus dignissimos accusamus distinctio quae explicabo incidunt
        ducimus, modi ipsam, iure omnis a. Assumenda, sunt maiores vel debitis
        cumque minus eum porro aperiam hic natus aliquid delectus tenetur! Magni
        fugiat quia exercitationem sapiente quisquam quod fuga consequatur
        temporibus, ipsum consequuntur incidunt eaque accusantium neque, sequi
        dicta adipisci perspiciatis iste veniam obcaecati officia quis? Nulla
        odit dolor itaque dolore, numquam nisi et molestiae consequatur
        voluptate repellat debitis, quisquam excepturi facere distinctio aperiam
        veritatis fugiat accusamus aliquam rem voluptas ducimus autem rerum
        enim? Dolorem error modi vel accusantium, beatae fugit saepe assumenda
        placeat nemo obcaecati explicabo repellendus nesciunt sunt architecto
        eveniet, recusandae illum ratione ex. Perferendis ullam nulla, ex
        delectus est eum blanditiis fugiat eos inventore illum repellendus,
        iusto et earum numquam reprehenderit labore officiis sapiente harum non
        amet! Ea eaque quo aliquam, non cumque, optio, sapiente explicabo
        laudantium odio quod iure.
      </p>
    </article>
  </div>
</section>
{% endblock %}

templates/index.html
    {% extends 'layout.html' %}
    {% block content %}
    <section class="row p-5">
      {% with messages = get_flashed_messages() %} 
        {% if messages %} 
          {% for message in messages %}
            <div class="col-9 mx-auto">
              <div class="alert alert-success alert-dismissible fade show" role="alert" >
                {{message}}
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
            </div>
      {% endfor %} {% endif %} {% endwith %}
      <article class="card card-body col-6">
        <h1>Add a contact</h1>
        <form method="POST" action="/new">
          <div class="mb-3">
            <label for="name" class="form-label">Write the name</label>
            <input type="text" class="form-control" id="name" name="fullname" />
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Write the email</label>
            <input type="text" class="form-control" id="email" name="email" />
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Write the phone</label>
            <input type="text" class="form-control" id="phone" name="phone" />
          </div>
          <button class="btn btn-primary">Save</button>
        </form>
      </article>
      <article class="card card-body col-6">
        <div>
          {% for contact in contacts %}
          <h5>{{contact.fullname}}</h5>
          <div>
            <a href="{{url_for('contacts.update', id=contact.id)}}">Update</a>
            <a href="{{url_for('contacts.delete', id=contact.id)}}">Delete</a>
          </div>
          <p>{{contact.email}}</p>
          <p>{{contact.phone}}</p>
          {%endfor%}
        </div>
      </article>
    </section>

    {% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Flask sqlalchemy</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Contacts App</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/update.html
    {% extends 'layout.html' %}
    {% block content %}
    <section class="row p-5">
      <div class="col-12 p-5">
        <article class="card card-body mx-auto" style="width: 50%">
          <h1>Update contact</h1>
          <form method="POST" action="/update/{{contact.id}}">
            <div class="mb-3">
              <label for="name" class="form-label">Update the name</label>
              <input
                type="text"
                class="form-control"
                id="name"
                name="fullname"
                value="{{contact.fullname}}"
              />
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Update the email</label>
              <input
                type="text"
                class="form-control"
                id="email"
                name="email"
                value="{{contact.email}}"
              />
            </div>
            <div class="mb-3">
              <label for="phone" class="form-label">Update the phone</label>
              <input
                type="text"
                class="form-control"
                id="phone"
                name="phone"
                value="{{contact.phone}}"
              />
            </div>
            <button class="btn btn-primary">Save</button>
          </form>
        </article>
      </div>
    </section>
    {% endblock %}